apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetty-demo-simple
  namespace: jetty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetty-demo-simple
  template:
    metadata:
      labels:
        app: jetty-demo-simple
    spec:
      #nodeSelector:
      #  simple-test-sidecar: "true"
      containers:
        - name: jetty-simple-server
          image: jettyproject/jetty-demo-simple:latest
          imagePullPolicy: Always
          args: ["jetty.ssl.sniHostCheck=false"]
          resources:
            limits:
              memory: "4Gi"
              cpu: "0.4"
            requests:
              memory: "4Gi"
              cpu: "0.4"
          ports:
            - containerPort: 8080
            - containerPort: 8443